# Обработка исключений try-except

`[Исключение, или ошибка]` - это ситуация, когда выполнение программы прерывается из-за какой-то проблемы или неожиданного условия во время выполнения кода.

`[Ошибка]` - это любое некорректное состояние или действие в программе, которое приводит к нежелательному результату. 
`[Исключение]` - механизм обработки ошибки, который прерывает выполнение программы, при возникновении ошибки. 

- Исключение это специальный объект в Python, который создается в ответ на ошибку во время выполнения программы. Когда возникает ошибка, Python автоматически создает объект-исключение определенного типа и поднимает его (raise), прерывая выполнение кода в текущем контексте.

<details>
  <summary>Общий шаблон инструкции try-except</summary>

```
try:
    # контролируемый код
except тип_ошибки_1:
    # код обработки ошибки (исключения)
except тип_ошибки_2:
    # код обработки ошибки (исключения)
...
except тип_ошибки_n:
    # код обработки ошибки (исключения)
else:
    # код для случая, если ошибки не было
finally:
    # код, который выполняется всегда
```
</details>

<details>
  <summary>Категории ошибок</summary>  
  
### Выделяют три основные категории ошибок:

<details>
  <summary>Синтаксическая ошибка</summary>  
  
 `[Синтаксическая ошибка]` -  это ошибка, возникающая из-за нарушения синтаксиса языка (Неправильное использование ключевых слов, операторов, скобок или отсутствия необходимых элементов, таких как двоеточия, запятые и т. д.).
 
<details>
  <summary>Основные исключения</summary>

- `SyntaxError`: Это наиболее общее исключение, которое возникает, когда Python не может распознать ваш код из-за ошибки в синтаксисе. Например, забытый двоеточие в конце условия или цикла.
- `IndentationError`: Это возникает, когда отступы в вашем коде не согласованы правильно. Python требует правильного выравнивания для обозначения блоков кода.
- `NameError`: Если вы пытаетесь использовать переменную, которая не была определена, Python вызовет это исключение.
- `TypeError`: Это происходит, когда вы пытаетесь выполнить операцию с объектом несовместимого типа.
- `ZeroDivisionError`: Когда попытка деления на ноль происходит
- `IndentationError`: Ошибка вызвана неправильным форматированием или выравниванием кода.
- `TabError`: Возникает, когда комбинируются табуляция и пробелы для создания отступов в коде.
- `ValueError`: Возникает, когда функция получает аргумент правильного типа, но с недопустимым значением.
</details>

</details>
<details>
  <summary>Ошибки времени выполнения</summary>

`[Ошибки времени выполнения]` - возникает, когда программа сталкивается с непредвиденной ситуацией во время выполнения, которая препятствует ее нормальному завершению (некорректные данные, неправильное использование функций или методов, или недоступность ресурсов).
<details>
  <summary>Основные исключения</summary>

1. `OverflowError`: Возникает, когда результат арифметической операции слишком велик для представления.
2. `IndexError`: Возникает, когда индекс последовательности находится вне допустимого диапазона.
3. `KeyError`: Возникает, когда словарь не содержит указанного ключа.
4. `FileNotFoundError`: Возникает, когда пытаемся открыть файл, который не существует.
5. `AttributeError`: Возникает, когда объект не имеет требуемого атрибута.
6. `ImportError`: Возникает, когда не удается импортировать модуль или его атрибут.
7. `MemoryError`: Возникает, когда недостаточно памяти для выполнения операции.
8. `KeyboardInterrupt`: Возникает, когда пользователь прерывает выполнение программы с клавиатуры (например, нажатием Ctrl+C).
9. `StopIteration`: Возникает, когда метод next() итератора вызывается, но итератор исчерпан.
10. `TypeError`: Возникает, когда операция применяется к объекту несовместимого типа.
11. `AssertionError`: Возникает, когда утверждение assert не проходит.
12. `RuntimeError`: Общее исключение для ошибок времени выполнения, которые не вписываются в другие категории.

</details>

</details>
<details>
  <summary>Логические ошибки</summary>

  `[Логические ошибки]` - (ошибка проектирования или ошибка алгоритма) - это ошибка в логике программы, которая приводит к некорректным результатам, хотя синтаксически и семантически код может быть правильным. Такие ошибки не вызывают исключений, потому что код технически выполняется без ошибок, но результат его работы не соответствует ожидаемому поведению.

</details>

</details>
<details>
  <summary>Коды возврата</summary>
  
- `[Код возврата]` - (код завершения или код возврата из процесса) - это целочисленное значение, возвращаемое программой при ее завершении. Этот код представляет собой способ сообщить вызывающему процессу или системе операций об успешном или неуспешном завершении программы и может содержать информацию о том, были ли выполнены какие-либо операции успешно или нет

<details>
  <summary>Пример</summary>

Метод `find()` используется для поиска подстроки в строке и возвращает индекс первого вхождения этой подстроки в строке. Если подстрока не найдена, метод возвращает -1. 
```
sentence = "Пример строки для поиска"
substring1 = "уют"
substring2 = 'строки'

index1 = sentence.find(substring1)
index2 = sentence.find(substring2)
print(index1) # -1
print(index2) # 7 
```
</details>
</details>
<details>
  <summary>Иерархия исключения</summary>

- `[BaseException]` - базовый класс самого верхнего уровня для всех прочих классов исключений.

- `[Exception]` - азовый класс для большинства встроенных в Python исключений.

- `[issubclass()]` - функция Для проверки родства классов исключений.
```
print(issubclass(IndexError, LookupError)) # True
```
- Если используется несколько блоков `except`, то первыми нужно указывать наиболее конкретные.
```
try:
    nums = [10, 5, 20, 25]
    print(nums[100])
except Exception:
    print('Произошла ошибка!')
except (KeyError, IndexError):
    print('Ошибка связанная с индексом!')
```

- Если нужен доступ к сгенерированному исключению как к объекту, то используется специальный синтаксис.
```
except (KeyError, IndexError) as err:
    pass

err - сгенерированный объект исключения.
```

- `[dir()]` - встроенная функция, позволяет посмотреть все все атрибуты объекта сгенерированного исключения.

<details>
  <summary>Иерархия исключений в Python</summary>

```
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
           +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```
</details>


</details>
<details>
  <summary>try-except</summary>

Конструкция `try-except` используется для обработки исключений в Python.

- `try`: Здесь помещается код, который может вызвать исключение.
- `except`: Если в блоке try произошло исключение, то выполнение кода переходит в блок except. Этот блок содержит код, который будет выполнен при возникновении исключения.
<details>
  <summary>Пример</summary>

```
try:
    result = 10 / 0 # Деление на ноль - ошибка и исключение ZeroDivisionError
except ZeroDivisionError:
    print("Деление на ноль!")
```
В блоке `try` происходит ошибка изза деления на ноль. Эта ошибка вызывает исключение `ZeroDivisionError`, которое обрабатывается в блоке `except`.
</details>
<details>
  <summary>Логика</summary>

Простыми словами:  
  
Конструкция try-except выступает в роли отсеивателя ошибок.  
  
В блок `try` помешается потенциально уязвимый к ошибкам код. 

Либо код отрабатывает без ошибок и программа продолжает работу в штатном режиме.  

Либо происходит ошибка, вызывается исключение, которое обрабатывается в блоке `except`.  

Блок `except` содержет код, который выполняется в случае возникновения ошибки.  

После выполнения кода в блоке `except` программа продолжает свое выполнение.  
</details>
<details>
  <summary>Обработка нескольких исключений</summary>
Если нужно обработать несколько типов исключений, можно использовать несколько блоков except или один блок except с перечислением исключений через запятую:

```
try:
    # контролируемый код
except тип_ошибки_1:
    # код обработки ошибки (исключения)
except тип_ошибки_2:
    # код обработки ошибки (исключения)
...
except тип_ошибки_n:
    # код обработки ошибки (исключения)
```
Или
```
try:
    # контролируемый код
except (тип_ошибки_1, тип_ошибки_2, ...):
    # обработка тип_ошибки_1 и(или) тип_ошибки_2
```

При обработке нескольких исключений, их нужно обрабатывать в порядке вероятности возникновения.

Первым обрабатывается наиболее конкретное исключение с наибольшей вероятностью возникновения.

Далее более общие исключения с меньшей вероятностью возникновения.

В ином варианте, общие исключения обработаются, затмив тем самым обработку более конкретного исключения.
</details>
<details>
  <summary>Не обязательные блоки else и finally</summary>

- `[else]` - располагается после всех блоков `except`. Выполняется только в том случае, если в боке `try` небыло ошибок.
- `[finaly]` - блок `finaly` располагается в самом конце конструкции `try-except` и выполняется вне зависимости произошла ошибка или нет.

     - Блок finally будет выполнен, даже если блок try содержит break, continue, return
     - При обработке ошибок внутри функции, блок  finally выполняется до инструкции return вне зависимости от их расположения в функции.

 <details>
  <summary>Шаблон использования</summary>

```
try:
    # контролируемый код
except тип_ошибки_1:
    # код обработки ошибки (исключения)
except тип_ошибки_2:
    # код обработки ошибки (исключения)
...
except тип_ошибки_n:
    # код обработки ошибки (исключения)
else:
    # код для случая, если ошибки не было
finally:
    # код, который выполняется всегда
```
</details>


</details>
<details>
  <summary>Исключение как объект</summary>

В Python все исключения являются подклассами (наследниками) базового класса `Exception` и являются объектами-исключений;

Эти объекты создаются при возникновении ошибки и содержат информацию о типе ошибки и контексте, в котором ошибка произошла;

Когда возникает ошибка, Python создает экземпляр соответствующего класса (объект-исключение) и передает его в блок except, где мы можем получить доступ к этому объекту и использовать его для вывода информации о возникшей ошибке;

```
try:
    # Попытка выполнить некорректное деление
    result = 10 / 0
except ZeroDivisionError as e:
    # Обработка исключения сохранения его как объект и вывод на печатьƒ
    print(e)  # division by zero
```


</details>
<details>
  <summary>Оператор raise</summary>


</details>

- `[raise]` - оператор позволяющий вручную возбуждать исключения при определённых условиях.

- Оператор `raise` используется для создания и возбуждения исключений  не входящих в класс `Exception`. Мы создаём при помощи оператора  `raise`  кастомное исключение и обрабатываем его блоком `try-except`.

- Информацию о перехвачены исключениях можно помещать в переменные при помощи ключевого слова `as` 
```
try:
  ...
  raise ...(...)
except Exception as err:
  ...
```
- Ключевое слово as используется в блоке except для связывания информации об исключении с переменной. Таким образом, мы можем использовать эту переменную для доступа к информации об исключении;

#

Конструктор любого исключения принимает переменное количество аргументов; 

Для того чтобы получить указанные значения, мы используем атрибут `args`, который является кортежем;

Синтаксис: 
```
raise [Exception]
raise [Exception(argument)]
raise [Exception(argument)] from [AnotherException]
```
   * `Exception` - класс исключения или объект исключения, которое нужно возбудить.
   * `argument` - это дополнительная информация, которую вы можете передать в исключение. 
   * `from [AnotherException]` - указание на другое исключение, от которого возбуждается текущее исключение (опционально)

1. Во первом варианте оператора raise указывается только название класса исключения.
```
raise ValueError
```
2. Во втором варианте оператора raise указывается экземпляр класса возбуждаемого исключения с аргументами при необходимости. Аргументов может быть несколько.
```
raise ValueError('Oпиcaниe исключения', 'Oпиcaниe исключения', ...)
```
<details>
  <summary>3. Третий вариант требует более детального разбора</summary>
  
`raise [Exception(argument)] from [AnotherException]`  

Конструкция `raise [Exception(argument)] from [AnotherException]` используется в Python для возбуждения исключения и указания на связанное исключение, которое может быть причиной первичного исключения.  

1. `raise [Exception(argument)]`:
    - Это базовая форма оператора raise, где [Exception(argument)] представляет собой класс исключения или объект исключения, которое мы хотим возбудить. [argument] - дополнительная информация об исключении. Например:  
```
raise ValueError("Некорректное значение!")
```
2. `from [AnotherException]`:
    - Это часть конструкции, указывающая на другое исключение, которое стало причиной возникновения текущего исключения. [AnotherException] - класс или объект другого исключения, от которого возникло текущее исключение.  
  
Пример:  

Предположим, у вас есть функция, которая пытается прочитать содержимое файла и выполнить какие-то операции с этим содержимым. Если файл не может быть прочитан, вы хотите вызвать пользовательское исключение FileProcessingError и указать на связанное исключение IOError.

```
def process_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            # Предположим, что здесь происходят какие-то операции с содержимым файла
            print("Файл успешно обработан.")
            # Ошибка ввода-вывода, такая как невозможность открыть несуществующий файл.
    except IOError as e:
        # Если не удалось прочитать файл, возбудим исключение FileProcessingError и укажем на связанное исключение IOError
        raise FileProcessingError(f"Ошибка обработки файла: {file_path}") from e

# Определяем пользовательское исключение FileProcessingError
class FileProcessingError(Exception):
    pass

# Пример использования функции
file_path = "несуществующий_файл.txt"
try:
    process_file(file_path)
except FileProcessingError as e:
    print(e)

В этом примере, если при попытке прочитать файл возникает исключение IOError,
мы вызываем пользовательское исключение FileProcessingError с дополнительной информацией о файле и указываем на связанное исключение e.
Это позволяет нам сохранить контекст ошибки и предоставить более информативное сообщение об ошибке.
```

</details>
</details>
<details>
  <summary>Пользовательские исключения</summary>

Для создания собственного типа исключения необходимо создать класс, являющийся потомком (наследником) одного из уже существующего типа исключения.  

Самым верным вариантом для наследовния является класс Exception.

```
class NegativeAgeError(Exception):
    pass
```
Приведённый код описывает новый тип исключения с именем NegativeAgeError, который является потомком класса Exception.  

Класс Exception содержит весь необходимый функционал, позволяющий работать с исключениями, поэтому в большинстве случаев достаточно создать пустой класс, который является потомком класса Exception.
```
class NegativeAgeError(Exception):
    pass

try:
    print('Введите свой возраст')
    age = int(input())
    if age < 0:
        raise NegativeAgeError('Возраст не может быть отрицательным')
    print('Ваш возраст равен', age)
except ValueError:
    print('Возраст должен быть числом')
except NegativeAgeError as e:
    print(e)
```

</details>
<details>
  <summary>7. Методики LBYL и EAFP</summary>

При написании программного кода, который может потенциально возбуждать исключения, существуют два основных подхода:

* `LBYL` (Look Before You Leap) — посмотри перед прыжком;
* `EAFP` (Easier to Ask Forgiveness than Permission) — проще извиниться, чем спрашивать разрешение;

Приведенный ниже код

```
data = {'Timur': 29, 'Ivan': 54}

data['Anri'] += 1
```

Приводит к возникновению исключения KeyError, поскольку ключ Anri отсутствует в словаре.
Мы можем исправить такой код двумя способами.

#

`LBYL`:  Перестраховаться и заранее проверить, что все получится. Это идеология LBYL-подхода. Сначала посмотрели, убедились, что все в порядке, только потом сделали.

```
data = {'Timur': 29, 'Ivan': 54}

if 'Anri' in data:
    data['Anri'] += 1
else:
    print('Ключ Anri отсутствует в словаре.')
```

#

`EAFP`: Мы можем описывать только главный алгоритм, рассчитывая, что все будет хорошо. Но при таком подходе необходимо прописать действия с исключениями (иногда разных типов). Это суть подхода EAFP.

```
data = {'Timur': 29, 'Ivan': 54}

try:
    data['Anri'] += 1
except KeyError:
    print('Ключ Anri отсутствует в словаре.')
```


</details>
<details>
  <summary>Оператор assert</summary>

`Оператор assert` – это встроенный оператор используемый для проверки того, является ли заданное утверждение истинным или ложным.  

Если утверждение истинно, то ничего не происходит и выполняется следующая строка кода.  

Если же утверждение ложно, оператор assert останавливает выполнение программы и подобно оператору raise возбуждает исключение AssertionError.

Синтаксис:
```
assert <утверждение>, <Дополнительная к исключению информация>
```
<details>
  <summary>Пример 1</summary>

```
age = 29                # возраст человека

assert age > 0, 'Возраст должен быть положительным числом'
```

Оператор `assert` используется для проверки того, является ли возраст положительным числом.  

В данном случае утверждение `age > 0` истинно, поэтому оператор assert ничего не делает.  

Если бы переменная age имела отрицательное значение, то оператором `assert` было бы возбуждено исключение `AssertionError`
</details>
<details>
  <summary>Пример 2</summary>

```
num1 = 20
num2 = 0

assert num2 != 0, 'Делитель равен нулю.'

print('Частное равно:', num1 / num2)
```

Оператор `assert` используется для проверки того, не равен ли нулю делитель.  

В данном случае утверждение `num2 != 0` ложно, поэтому оператором `assert` будет возбуждено исключение `AssertionError` вместе с добавленным нами сообщением.

Если изменить значение переменной `num2` на `10` и выполнить нашу программу снова, то на этот раз утверждение `num2 != 0` окажется истинным и исключение возбуждено не будет. 

Таким образом, на экран выведется результат деления: `Частное равно: 2.0`
</details>

#

- `Оператор assert` — это средство отладки, которое проверяет утверждение, выступающее в качестве внутренней самопроверки вашей программы;

- `Оператор assert` должен применяться только для того чтобы помогать разработчикам идентифицировать ошибки. Он не является механизмом обработки ошибок;

- `Оператор assert` может быть глобально отключен в настройках интерпретатора;

- `assert` – это именно оператор, а не функция. При использовании assert мы не указываем круглые скобки;

</details>
<details>
  <summary>Список кодов состояния HTTP</summary>

`Код состояния HTTP` (англ. HTTP status code) — часть первой строки ответа сервера при запросах по протоколу HTTP.  

Он представляет собой целое трёхразрядное десятичное число. Первая цифра указывает на класс состояния. За кодом ответа обычно следует отделённая пробелом поясняющая фраза на английском языке, которая разъясняет человеку причину именно такого ответа. Примеры:
```
201 Webpage Created
404 Not Found 
507 Insufficient Storage
```

#

<details>
  <summary>1xx: Informational (информационные)</summary>

В этот класс выделены коды, информирующие о процессе передачи. При работе через протокол версии 1.0 сообщения с такими кодами должны игнорироваться. В версии 1.1 клиент должен быть готов принять этот класс сообщений как обычный ответ, но серверу отправлять что-либо не нужно. Сами сообщения от сервера содержат только стартовую строку ответа и, если требуется, несколько специфичных для ответа полей заголовка. Прокси-серверы подобные сообщения должны отправлять дальше от сервера к клиенту.

- `100 Continue` — сервер удовлетворён начальными сведениями о запросе, клиент может продолжать пересылать заголовки. Появился в HTTP/1.1.

- `101 Switching Protocols` — сервер выполняет требование клиента и переключает протоколы в соответствии с указанием, данным в поле заголовка Upgrade. Сервер отправляет заголовок ответа Upgrade, указывая протокол, на который он переключился. Появился в HTTP/1.1.

- `102 Processing` — запрос принят, но на его обработку понадобится длительное время. Используется сервером, чтобы клиент не разорвал соединение из-за превышения времени ожидания. Клиент при получении такого ответа должен сбросить таймер и дожидаться следующей команды в обычном режиме. Появился в WebDAV.

- `103 Early Hints` — используется для раннего возврата части заголовков, когда заголовки полного ответа не могут быть быстро сформированы.
</details>

- `100 Continue` («продолжайте»)[3];
- `101 Switching Protocols` («переключение протоколов»)[3];
- `102 Processing` («идёт обработка»);
- `103 Early Hints` («ранняя метаинформация»);

<details>
  <summary>2xx: Success (успешно)</summary>

Сообщения данного класса информируют о случаях успешного принятия и обработки запроса клиента. В зависимости от статуса сервер может ещё передать заголовки и тело сообщения.

- `200 OK` — успешный запрос. Если клиентом были запрошены какие-либо данные, то они находятся в заголовке и/или теле сообщения. Появился в HTTP/1.0.

- `201 Created` — в результате успешного выполнения запроса был создан новый ресурс. Сервер может указать адреса (их может быть несколько) созданного ресурса в теле ответа, при этом предпочтительный адрес указывается в заголовке Location. Серверу рекомендуется указывать в теле ответа характеристики созданного ресурса и его адреса, формат тела ответа определяется заголовком Content-Type. При обработке запроса новый ресурс должен быть создан до отправки ответа клиенту, иначе следует использовать ответ с кодом 202. Появился в HTTP/1.0.

- `202 Accepted` — запрос был принят на обработку, но она не завершена. Клиенту не обязательно дожидаться окончательной передачи сообщения, так как может быть начат очень долгий процесс. Появился в HTTP/1.0.

- `203 Non-Authoritative Information` — аналогично ответу 200, но в этом случае передаваемая информация была взята не из первичного источника (резервной копии, другого сервера и т. д.) и поэтому может быть неактуальной. Появился в HTTP/1.1.

- `204 No Content` — сервер успешно обработал запрос, но в ответе были переданы только заголовки без тела сообщения. Клиент не должен обновлять содержимое документа, но может применить к нему полученные метаданные. Появился в HTTP/1.0.

- `205 Reset Content` — сервер обязывает клиента сбросить введённые пользователем данные. Тела сообщения сервер при этом не передаёт и документ обновлять не обязательно. Появился в HTTP/1.1.

- `206 Partial Content` — сервер удачно выполнил частичный GET-запрос, возвратив только часть сообщения. В заголовке Content-Range сервер указывает байтовые диапазоны содержимого. Особое внимание при работе с подобными ответами следует уделить кэшированию. Появился в HTTP/1.1. (подробнее…)

- `207 Multi-Status` — сервер передаёт результаты выполнения сразу нескольких независимых операций. Они помещаются в само тело сообщения в виде XML-документа с объектом multistatus. Не рекомендуется размещать в этом объекте статусы из серии 1xx из-за бессмысленности и избыточности. Появился в WebDAV.

- `208 Already Reported` — члены привязки DAV уже были перечислены в предыдущей части (multistatus) ответа и не включаются снова.

- `226 IM Used` — заголовок A-IM от клиента был успешно принят и сервер возвращает содержимое с учётом указанных параметров. Введено в RFC 3229 для дополнения протокола HTTP поддержкой дельта-кодирования.

</details>

- `200 OK` («хорошо»);
- `201 Created` («создано»);
- `202 Accepted` («принято»);
- `203 Non-Authoritative Information` («информация не авторитетна»);
- `204 No Content` («нет содержимого»);
- `205 Reset Content` («сбросить содержимое»);
- `206 Partial Content` («частичное содержимое»);
- `207 Multi-Status` («многостатусный»);
- `208 Already Reported` («уже сообщалось»);
- `226 IM Used` («использовано IM»).

<details>
  <summary>3xx: Redirection (перенаправление)</summary>

Коды этого класса сообщают клиенту, что для успешного выполнения операции необходимо сделать другой запрос, как правило, по другому URI. Из данного класса пять кодов 301, 302, 303, 305 и 307 относятся непосредственно к перенаправлениям. Адрес, по которому клиенту следует произвести запрос, сервер указывает в заголовке Location. При этом допускается использование фрагментов в целевом URI.

- `300 Multiple Choices` — по указанному URI существует несколько вариантов предоставления ресурса по типу MIME, по языку или по другим характеристикам. Сервер передаёт с сообщением список альтернатив, давая возможность сделать выбор клиенту автоматически или пользователю. Появился в HTTP/1.0.

- `301 Moved Permanently` — запрошенный документ был окончательно перенесен на новый URI, указанный в поле Location заголовка. Если клиент хранит данный URI, то его следует заменить на новый. Некоторые клиенты некорректно ведут себя при обработке данного кода. Появился в HTTP/1.0.

- `302 Found, 302 Moved Temporarily — запрошенный документ временно доступен по другому URI, указанному в заголовке в поле Location. Этот код может быть использован, например, при управляемом сервером согласовании содержимого. Некоторые[какие?] клиенты некорректно ведут себя при обработке данного кода. Введено в HTTP/1.0.

- `303 See Other` — документ по запрошенному URI нужно запросить по адресу в поле Location заголовка с использованием метода GET несмотря даже на то, что первый запрашивался иным методом. Этот код был введён вместе с кодом 307 для избежания неоднозначности, чтобы сервер был уверен, что следующий ресурс будет запрошен методом GET. Например, на веб-странице есть поле ввода текста для быстрого перехода и поиска. После ввода данных браузер делает запрос методом POST, включая в тело сообщения введённый текст. Если обнаружен документ с введённым названием, то сервер отвечает кодом 303, указав в заголовке Location его постоянный адрес. Тогда браузер гарантировано его запросит методом GET для получения содержимого. В противном случае сервер просто вернёт клиенту страницу с результатами поиска. Введено в HTTP/1.1.

- `304 Not Modified` — сервер возвращает такой код, если клиент запросил документ методом GET, использовал заголовок If-Modified-Since или If-None-Match и документ не изменился с указанного момента. При этом сообщение сервера не должно содержать тела. Появился в HTTP/1.0.

- `305 Use Proxy` — запрос к запрашиваемому ресурсу должен осуществляться через прокси-сервер, URI которого указан в поле Location заголовка. Данный код ответа могут использовать только исходные HTTP-сервера (не прокси). Введено в HTTP/1.1.

- `306 (зарезервировано)` — использовавшийся в ранних версиях спецификации код ответа, в настоящий момент зарезервирован. Упомянут в RFC 2616 (обновление HTTP/1.1). Согласно ранним наброскам, код означал Switch Proxy, указывая клиенту сменить используемый прокси-сервер на указанный сервером в заголовке ответа.

- `307 Temporary Redirect — запрашиваемый ресурс на короткое время доступен по другому URI, указанный в поле Location заголовка. Метод запроса (GET/POST) менять не разрешается. Например, POST-запрос должен быть отправлен по новому URI тем же методом POST. Этот код был введён вместе с 303-м вместо 302-го для избежания неоднозначности. Введено в RFC 2616 (обновление HTTP/1.1).

- `308 Permanent Redirect — запрашиваемый ресурс был окончательно перенесен на новый URI, указанный в поле Location заголовка. Метод запроса (GET/POST) менять не разрешается. Например, POST-запрос должен быть отправлен по новому URI тем же методом POST. Этот код был введён вместо 301-го для избежания неоднозначности.

</details>

- `300 Multiple Choices` («множество выборов»);
- `301 Moved Permanently` («перемещено навсегда»);
- `302 Found` («найдено»);
- `303 See Other` («смотреть другое»);
- `304 Not Modified` («не изменялось»);
- `305 Use Proxy` («использовать прокси»);
- `306 зарезервировано` (код использовался только в ранних спецификациях);
- `307 Temporary Redirect` («временное перенаправление»);
- `308 Permanent Redirect` («постоянное перенаправление»);

<details>
  <summary>4xx: Client Error (ошибка клиента)</summary>

Класс кодов 4xx предназначен для указания ошибок со стороны клиента. При использовании всех методов, кроме HEAD, сервер должен вернуть в теле сообщения гипертекстовое пояснение для пользователя.

- `400 Bad Request` — сервер обнаружил в запросе клиента синтаксическую ошибку. Появился в HTTP/1.0.

- `401 Unauthorized` — для доступа к запрашиваемому ресурсу требуется аутентификация. В заголовке ответ должен содержать поле WWW-Authenticate с перечнем условий аутентификации. Иными словами, для доступа к запрашиваемому ресурсу клиент должен представиться, послав запрос, включив при этом в заголовок сообщения поле Authorization с требуемыми для аутентификации данными. Если запрос уже включает данные для авторизации, ответ 401 означает, что в авторизации с ними отказано.

- `402 Payment Required` — предполагается использовать в будущем[когда?]. В настоящий момент[когда?] не используется. Этот код предусмотрен для платных пользовательских сервисов, и некорректно выдавать его хостинг-провайдерам, если хозяин сайта не оплатил их услуги. Зарезервирован, начиная с HTTP/1.1.

- `403 Forbidden` — сервер понял запрос, но он отказывается его выполнять из-за ограничений в доступе для клиента к указанному ресурсу. Иными словами, клиент не уполномочен совершать операции с запрошенным ресурсом. Если для доступа к ресурсу требуется аутентификация средствами HTTP, то сервер вернёт ответ 401, или 407 при использовании прокси. В противном случае ограничения были заданы администратором сервера или разработчиком веб-приложения и могут быть любыми в зависимости от возможностей используемого программного обеспечения. В любом случае серверу следует сообщить причины отказа в обработке запроса. Наиболее вероятными причинами ограничения может послужить попытка доступа к системным ресурсам веб-сервера (например, файлам .htaccess или .htpasswd) или к файлам, доступ к которым был закрыт с помощью конфигурационных файлов, требование аутентификации не средствами HTTP, например, для доступа к системе управления содержимым или разделу для зарегистрированных пользователей либо сервер не удовлетворён IP-адресом клиента, например, при блокировках. Появился в HTTP/1.0.

- `404 Not Found` — самая распространённая ошибка при пользовании Интернетом, основная причина — ошибка в написании адреса Web-страницы. Сервер понял запрос, но не нашёл соответствующего ресурса по указанному URL. Если серверу известно, что по этому адресу был документ, то ему желательно использовать код 410. Ответ 404 может использоваться вместо 403, если требуется тщательно скрыть от посторонних глаз определённые ресурсы. Появился в HTTP/1.0.

- `405 Method Not Allowed` — указанный клиентом метод нельзя применить к текущему ресурсу. В ответе сервер должен указать доступные методы в заголовке Allow, разделив их запятой. Эту ошибку сервер должен возвращать, если метод ему известен, но он не применим именно к указанному в запросе ресурсу, если же указанный метод не применим на всём сервере, то клиенту нужно вернуть код 501 (Not Implemented). Появился в HTTP/1.1.

- `406 Not Acceptable` — запрошенный URI не может удовлетворить переданным в заголовке характеристикам. Если метод был не HEAD, то сервер должен вернуть список допустимых характеристик для данного ресурса. Появился в HTTP/1.1.

- `407 Proxy Authentication Required` — ответ аналогичен коду 401 за исключением того, что аутентификация производится для прокси-сервера. Механизм аналогичен идентификации на исходном сервере. Появился в HTTP/1.1.

- `408 Request Timeout` — время ожидания сервером передачи от клиента истекло. Клиент может повторить аналогичный предыдущему запрос в любое время. Например, такая ситуация может возникнуть при загрузке на сервер объёмного файла методом POST или PUT. В какой-то момент передачи источник данных перестал отвечать, например, из-за повреждения компакт-диска или потери связи с другим компьютером в локальной сети. Пока клиент ничего не передаёт, ожидая от него ответа, соединение с сервером держится. Через некоторое время сервер может закрыть соединение со своей стороны, чтобы дать возможность другим клиентам сделать запрос. Этот ответ не возвращается, когда клиент принудительно остановил передачу по команде пользователя или соединение прервалось по каким-то иным причинам, так как ответ уже послать невозможно. Появился в HTTP/1.1.

- `409 Conflict` — запрос не может быть выполнен из-за конфликтного обращения к ресурсу. Такое возможно, например, когда два клиента пытаются изменить ресурс с помощью метода PUT. Появился в HTTP/1.1.

- `410 Gone` — такой ответ сервер посылает, если ресурс раньше был по указанному URL, но был удалён и теперь недоступен. Серверу в этом случае неизвестно и местоположение альтернативного документа (например копии). Появился в HTTP/1.1.

- `411 Length Required` — для указанного ресурса клиент должен указать Content-Length в заголовке запроса. Без указания этого поля не стоит делать повторную попытку запроса к серверу по данному URI. Такой ответ естественен для запросов типа POST и PUT. Например, если по указанному URI производится загрузка файлов, а на сервере стоит ограничение на их объём. Тогда разумней будет проверить в самом начале заголовок Content-Length и сразу отказать в загрузке, чем провоцировать бессмысленную нагрузку, разрывая соединение, когда клиент действительно пришлёт слишком объёмное сообщение. Появился в HTTP/1.1.

- `412 Precondition Failed` — возвращается, если ни одно из условных полей заголовка (If-Match и др., см. RFC 7232) запроса не было выполнено. Появился в HTTP/1.1.

- `413 Payload Too Large` — возвращается в случае, если сервер отказывается обработать запрос по причине слишком большого размера тела запроса. Сервер может закрыть соединение, чтобы прекратить дальнейшую передачу запроса. Если проблема временная, то рекомендуется в ответ сервера включить заголовок Retry-After с указанием времени, по истечении которого можно повторить аналогичный запрос. Появился в HTTP/1.1. Ранее назывался «Request Entity Too Large».

- `414 URI Too Long` — сервер не может обработать запрос из-за слишком длинного указанного URI. Такую ошибку можно спровоцировать, например, когда клиент пытается передать длинные параметры через метод GET, а не POST. Появился в HTTP/1.1. Ранее назывался «Request-URI Too Long».

- `415 Unsupported Media Type` — по каким-то причинам сервер отказывается работать с указанным типом данных при данном методе. Появился в HTTP/1.1.

- `416 Range Not Satisfiable` — в поле Range заголовка запроса был указан диапазон за пределами ресурса и отсутствует поле If-Range. Если клиент передал байтовый диапазон, то сервер может вернуть реальный размер в поле Content-Range заголовка. Данный ответ не следует использовать при передаче типа multipart/byteranges[источник не указан 4429 дней]. Введено в RFC 2616 (обновление HTTP/1.1). Ранее назывался «Requested Range Not Satisfiable».

- `417 Expectation Failed` — по каким-то причинам сервер не может удовлетворить значению поля Expect заголовка запроса. Введено в RFC 2616 (обновление HTTP/1.1).

- `418 I’m a teapot` — Этот код был введен в 1998 году как одна из традиционных первоапрельских шуток IETF в RFC 2324, Hyper Text Coffee Pot Control Protocol. Данный код поддерживается большинством реальных серверов.

- `419 Authentication Timeout (not in RFC 2616) — Этого кода нет в RFC 2616, используется в качестве альтернативы коду 401, которые прошли проверку подлинности, но лишены доступа к определённым ресурсам сервера. Обычно код отдается, если CSRF-токен устарел или оказался некорректным.

- `421 Misdirected Request` — запрос был перенаправлен на сервер, не способный дать ответ.

- `422 Unprocessable Entity` — сервер успешно принял запрос, может работать с указанным видом данных (например, в теле запроса находится XML-документ, имеющий верный синтаксис), однако имеется какая-то логическая ошибка, из-за которой невозможно произвести операцию над ресурсом. Введено в WebDAV.

- `423 Locked` — целевой ресурс из запроса заблокирован от применения к нему указанного метода. Введено в WebDAV.

- `424 Failed Dependency` — реализация текущего запроса может зависеть от успешности выполнения другой операции. Если она не выполнена и из-за этого нельзя выполнить текущий запрос, то сервер вернёт этот код. Введено в WebDAV.

- `425 Too Early` — сервер не готов принять риски обработки «ранней информации». Введено в RFC 8470 для защиты от атак повторения при использовании 0-RTT в TLS 1.3.

- `426 Upgrade Required` — сервер указывает клиенту на необходимость обновить протокол. Заголовок ответа должен содержать правильно сформированные поля Upgrade и Connection. Введено в RFC 2817 для возможности перехода к TLS посредством HTTP.

- `428 Precondition Required` — сервер указывает клиенту на необходимость использования в запросе заголовков условий, наподобие If-Match. Введено в черновике стандарта RFC 6585.

- `429 Too Many Requests` — клиент попытался отправить слишком много запросов за короткое время, что может указывать, например, на попытку DDoS-атаки. Может сопровождаться заголовком Retry-After, указывающим, через какое время можно повторить запрос. Введено в черновике стандарта RFC 6585.

- `431 Request Header Fields Too Large` — Превышена допустимая длина заголовков. Сервер не обязан отвечать этим кодом, вместо этого он может просто сбросить соединение. Введено в черновике стандарта RFC 6585.

- `449 Retry With` — возвращается сервером, если для обработки запроса от клиента поступило недостаточно информации. При этом в заголовок ответа помещается поле Ms-Echo-Request. Введено корпорацией Microsoft для WebDAV. В настоящий момент[когда?] используется как минимум программой Microsoft Money.

- `451 Unavailable For Legal Reasons` — доступ к ресурсу закрыт по юридическим причинам, например, по требованию органов государственной власти или по требованию правообладателя в случае нарушения авторских прав. Введено в черновике IETF за авторством Google, при этом код ошибки является отсылкой к роману Рэя Брэдбери «451 градус по Фаренгейту». Был добавлен в стандарт 21 декабря 2015 года.

- `499 Client Closed Request` — нестандартный код, предложенный и используемый nginx для случаев, когда клиент закрыл соединение, пока nginx обрабатывал запрос.
</details>

- `400 Bad Request` («неправильный, некорректный запрос»);
- `401 Unauthorized` («не авторизован»);
- `402 Payment Required` («необходима оплата») — зарезервировано для использования в будущем;
- `403 Forbidden` («запрещено (не уполномочен)»);
- `404 Not Found` («не найдено»);
- `405 Method Not Allowed` («метод не поддерживается»);
- `406 Not Acceptable` («неприемлемо»);
- `407 Proxy Authentication Required` («необходима аутентификация прокси»);
- `408 Request Timeout` («истекло время ожидания»);
- `409 Conflict` («конфликт»);
- `410 Gone` («удалён»);
- `411 Length Required` («необходима длина»);
- `412 Precondition Failed` («условие ложно»);
- `413 Payload Too Large` («полезная нагрузка слишком велика»);
- `414 URI Too Long` («URI слишком длинный»);
- `415 Unsupported Media Type` («неподдерживаемый тип данных»);
- `416 Range Not Satisfiable` («диапазон не достижим»);
- `417 Expectation Failed` («ожидание не оправдалось»);
- `418 I’m a teapot` («я — чайник»);
- `419 Authentication Timeout` (not in RFC 2616) («обычно ошибка проверки CSRF»);
- `421 Misdirected Request`;
- `422 Unprocessable Entity` («необрабатываемый экземпляр»);
- `423 Locked` («заблокировано»);
- `424 Failed Dependency` («невыполненная зависимость»);
- `425 Too Early` («слишком рано»);
- `426 Upgrade Required` («необходимо обновление»);
- `428 Precondition Required` («необходимо предусловие»);
- `429 Too Many Requests` («слишком много запросов»);
- `431 Request Header Fields Too Large` («поля заголовка запроса слишком большие»);
- `449 Retry With` («повторить с»);
- `451 Unavailable For Legal Reasons` («недоступно по юридическим причинам»);
- `499 Client Closed Request` (клиент закрыл соединение);

<details>
  <summary>5xx: Server Error (ошибка сервера)</summary>

Коды 5xx выделены под случаи необработанных исключений при выполнении операций на стороне сервера. Для всех ситуаций, кроме использования метода HEAD, сервер должен включать в тело сообщения объяснение, которое клиент отобразит пользователю.

- `500 Internal Server Error` — любая внутренняя ошибка сервера, которая не входит в рамки остальных ошибок класса. Появился в HTTP/1.0.

- `501 Not Implemented` — сервер не поддерживает возможностей, необходимых для обработки запроса. Типичный ответ для случаев, когда сервер не понимает указанный в запросе метод. Если же метод серверу известен, но он не применим к данному ресурсу, то нужно вернуть ответ 405. Появился в HTTP/1.0.

- `502 Bad Gateway` — сервер, выступая в роли шлюза или прокси-сервера, получил недействительное ответное сообщение от вышестоящего сервера. Появился в HTTP/1.0.

- `503 Service Unavailable` — сервер временно не имеет возможности обрабатывать запросы по техническим причинам (обслуживание, перегрузка и прочее). В поле Retry-After заголовка сервер может указать время, через которое клиенту рекомендуется повторить запрос. Хотя во время перегрузки очевидным кажется сразу разрывать соединение, эффективней может оказаться установка большого значения поля Retry-After для уменьшения частоты избыточных запросов. Появился в HTTP/1.0.

- `504 Gateway Timeout` — сервер в роли шлюза или прокси-сервера не дождался ответа от вышестоящего сервера для завершения текущего запроса. Появился в HTTP/1.1.

- `505 HTTP Version Not Supported` — сервер не поддерживает или отказывается поддерживать указанную в запросе версию протокола HTTP. Появился в HTTP/1.1.

- `506 Variant Also Negotiates` — в результате ошибочной конфигурации выбранный вариант указывает сам на себя, из-за чего процесс связывания прерывается. Экспериментальное. Введено в RFC 2295 для дополнения протокола HTTP технологией Transparent Content Negotiation.

- `507 Insufficient Storage` — не хватает места для выполнения текущего запроса. Проблема может быть временной. Введено в WebDAV.

- `508 Loop Detected` — операция отменена, так как сервер обнаружил бесконечный цикл при обработке запроса без ограничения глубины. Введено в WebDAV.

- `508 Resource Limit Reached` — вариант ошибки 508 в CloudLinux, возникающий при исчерпании лимитов хостинга.

- `509 Bandwidth Limit Exceeded` — используется при превышении веб-площадкой отведённого ей ограничения на потребление трафика. В данном случае владельцу площадки следует обратиться к своему хостинг-провайдеру. В настоящий момент данный код не описан ни в одном RFC и используется только модулем «bw/limited», входящим в панель управления хостингом cPanel, где и был введён.

- `510 Not Extended` — на сервере отсутствует расширение, которое желает использовать клиент. Сервер может дополнительно передать информацию о доступных ему расширениях. Введено в RFC 2774 для дополнения протокола HTTP поддержкой расширений.

- `511 Network Authentication Required` — этот ответ посылается не сервером, которому был предназначен запрос, а сервером-посредником — например, сервером провайдера — в случае, если клиент должен сначала авторизоваться в сети, например, ввести пароль для платной точки доступа к Интернету. Предполагается, что в теле ответа будет возвращена Web-форма авторизации или перенаправление на неё. Введено в черновике стандарта RFC 6585.

- `520 Unknown Error`, возникает когда сервер CDN не смог обработать ошибку веб-сервера; нестандартный код CloudFlare.

- `521 Web Server Is Down`, возникает когда подключения CDN отклоняются веб-сервером; нестандартный код CloudFlare.

- `522 Connection Timed Out`, возникает когда CDN не удалось подключиться к веб-серверу; нестандартный код CloudFlare.

- `523 Origin Is Unreachable`, возникает когда веб-сервер недостижим; нестандартный код CloudFlare.

- `524 A Timeout Occurred`, возникает при истечении тайм-аута подключения между сервером CDN и веб-сервером; нестандартный код CloudFlare.

- `525 SSL Handshake Failed`, возникает при ошибке рукопожатия SSL между сервером CDN и веб-сервером; нестандартный код CloudFlare.

- `526 Invalid SSL Certificate`, возникает когда не удаётся подтвердить сертификат шифрования веб-сервера; нестандартный код CloudFlare.
</details>

- `500 Internal Server Error` («внутренняя ошибка сервера»);
- `501 Not Implemented` («не реализовано»);
- `502 Bad Gateway` («плохой, ошибочный шлюз»);
- `503 Service Unavailable` («сервис недоступен»);
- `504 Gateway Timeout` («шлюз не отвечает»);
- `505 HTTP Version Not Supported` («версия HTTP не поддерживается»);
- `506 Variant Also Negotiates` («вариант тоже проводит согласование»);
- `507 Insufficient Storage` («переполнение хранилища»);
- `508 Loop Detected` («обнаружено бесконечное перенаправление»);
- `509 Bandwidth Limit Exceeded` («исчерпана пропускная ширина канала»);
- `510 Not Extended` («не расширено»);
- `511 Network Authentication Required` («требуется сетевая аутентификация»);
- `520 Unknown Error` («неизвестная ошибка»);
- `521 Web Server Is Down` («веб-сервер не работает»);
- `522 Connection Timed Out` («соединение не отвечает»);
- `523 Origin Is Unreachable` («источник недоступен»);
- `524 A Timeout Occurred` («время ожидания истекло»);
- `525 SSL Handshake Failed` («квитирование SSL не удалось»);
- `526 Invalid SSL Certificate` («недействительный сертификат SSL»);


</details>
































#
<details>
  <summary></summary>


</details>
